### ISSUE TITLE
Small correction for this to work in Ubuntu 22.04

### ISSUE THREAD

**Issue by sulph68** [xuancong84/indicator-cpufreq#1]
the existing code doesn't seem to work in Ubuntu22.04 as the GTK version has changed.
the below patch on `indicator.py` will allow this useful applet to work again.

```
# FIXME:
# org.freedesktop.PolicyKit1 (cheat at distutils-extra)

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')

```

**Comment by DjZU** [comment]
Thank you @sulph68

**Comment by marotoweb** [comment]
I updated Ubuntu and came across an error message the first time I rebooted, phenomenal when I questioned ChatGPT with this error and it recommended that same code change

**Comment by Antimailer** [comment]
Thanks @sulph68  for sharing :+1:

**Comment by xuancong84** [comment]
Thanks! Patch applied.
